<?php if (!defined('INVOICE_VIEW')) { http_response_code(404); exit; } $hasMore=count($batches)>20; $batches=array_slice($batches,0,20); ?>
<section class="card"><h2><?= it('tab_activity') ?></h2><?php require $viewRoot.'/filters.php'; ?><a data-save-context="page" data-save-context-target="#invoice-results" class="invoice-link-action" href="<?= ie(invoiceUrl('activity',['state'=>$filters['state']])) ?>"><?= it('refresh') ?></a></section>
<div id="invoice-results">
<?php if (!$batches && !$legacyTasks): ?><section class="card"><p><?= it('no_runs') ?></p></section><?php endif; ?>
<?php foreach ($batches as $batch): $sum=$batch['summary']; ?><section class="card"><div class="invoice-record-heading"><h2><?= it('collection_request') ?> #<?= (int)$batch['id'] ?></h2><?php invoiceStatus($sum['state']); ?></div><p><?= ie(invoiceTime($batch['created_at'])) ?> · <?= it('source_'.$batch['source']) ?> · <?= ie($batch['period']) ?></p>
<dl class="invoice-facts"><div><dt><?= it('accounts_completed') ?></dt><dd><?= $sum['completed'] ?>/<?= $sum['total'] ?></dd></div><div><dt><?= it('accounts_failed') ?></dt><dd><?= $sum['failed'] ?></dd></div><div><dt><?= it('accounts_running') ?></dt><dd><?= $sum['running'] ?></dd></div><div><dt><?= it('counts') ?></dt><dd><?= $sum['new'] ?>/<?= $sum['duplicates'] ?></dd></div></dl>
<?php if ($batch['retry_of']): ?><p><?= it('retry_of') ?> #<?= (int)$batch['retry_of'] ?></p><?php endif; ?>
<?php if ($canRun && $sum['failed']): ?><form method="post"><?php invoiceHidden('retry_batch'); ?><input type="hidden" name="batch_id" value="<?= (int)$batch['id'] ?>"><button class="primary-button"><?= it('retry_failed') ?></button></form><p><?= it('retry_ready_note') ?></p><?php endif; ?>
<details <?= in_array($sum['state'],['running','failed','partial'],true)?'open':'' ?>><summary><?= it('request_details') ?></summary><p><?= it('results_filtered') ?></p><?php foreach ($batch['tasks'] as $job) invoiceTaskCard($job); ?></details></section><?php endforeach; ?>
<?php if ($hasMore): ?><a data-save-context="page" data-save-context-target="#invoice-results" class="invoice-link-action" href="<?= ie(invoiceUrl('activity',['state'=>$filters['state'],'before'=>end($batches)['id']])) ?>"><?= it('older_requests') ?></a><?php endif; ?>
<?php if ($legacyTasks): ?><section id="invoice-legacy-results" class="card"><h2><?= it('individual_operations') ?></h2><p><?= it('individual_note') ?></p><?php foreach (array_slice($legacyTasks,0,50) as $job) invoiceTaskCard($job); ?><?php if (count($legacyTasks)>50): ?><a data-save-context="page" data-save-context-target="#invoice-legacy-results" class="invoice-link-action" href="<?= ie(invoiceUrl('activity',['state'=>$filters['state'],'task_before'=>$legacyTasks[49]['id']])) ?>"><?= it('older_requests') ?></a><?php endif; ?></section><?php endif; ?>
</div>
<?php if ($isGerente && ($driveAlerts || $alerts)): ?><section class="card"><details><summary><?= it('alert_history') ?></summary><p><?= it('alert_history_scope') ?></p><ul class="invoice-alerts"><?php foreach (array_merge($driveAlerts,$alerts) as $alert): ?><li><?= ie($alert['account_label']) ?> · <?= ie($alert['period']) ?> · <?php invoiceStatus('alert_'.$alert['state']); ?><small><?= ie(invoiceTime($alert['created_at'])) ?></small></li><?php endforeach; ?></ul></details></section><?php endif; ?>
