<?php if (!defined('INVOICE_VIEW')) { http_response_code(404); exit; } $hasMore=count($documents)>50; $documents=array_slice($documents,0,50); ?>
<section class="card"><h2><?= it('tab_documents') ?></h2><?php require $viewRoot.'/filters.php'; ?></section>
<section id="invoice-results" class="card"><h2><?= it('invoices') ?></h2><?php if (!$documents): ?><p><?= it('empty') ?></p><?php endif; ?>
<div class="invoice-record-grid"><?php foreach ($documents as $d): ?><article class="invoice-record"><div class="invoice-record-heading"><h3><?= ie($d['invoice_number']) ?></h3><?php invoiceStatus($d['pipeline_state']); ?></div><p><?= ie(InvoiceAccounts::PORTALS[$d['portal']].' — '.$d['account_label']) ?></p>
<dl class="invoice-facts"><div><dt><?= it('property') ?></dt><dd><?= ie($d['property_label'] ?? $d['property_id']) ?></dd></div><div><dt><?= it('date') ?></dt><dd><?= ie($d['issued_on'] ?? '—') ?></dd></div><div><dt><?= it('period') ?></dt><dd><?= ie($d['period']) ?> · <?= it($d['period_basis']) ?></dd></div><div><dt><?= it('company') ?></dt><dd><?php invoiceStatus($d['company_state'] ?? 'review'); ?></dd></div><div><dt>Google Drive</dt><dd><?php invoiceStatus('drive_'.($d['drive_state'] ?? 'pending')); ?></dd></div><div><dt>TOConline</dt><dd><?php invoiceStatus($d['toconline_state']==='pending'?'integration_unavailable':($d['toconline_state'] ?? 'integration_unavailable'),$d['toconline_state']==='pending'?'toconline_setup_pending':null); ?></dd></div></dl>
<?php if ($d['portal']==='airbnb'): ?><ol class="invoice-pipeline"><li><?= it('csv_received') ?></li><li><?= it('csv_pending') ?></li><li><?= it('pdf_pending') ?></li><li><?= it('toconline_setup_pending') ?></li></ol><?php endif; ?>
<div class="form-actions"><a class="primary-button" href="invoice-download.php?document=<?= (int)$d['id'] ?>"><?= it($d['drive_state']==='verified'?'open_drive':'download') ?> · <?= ie(strtoupper($d['format'])) ?></a><?php if ($isGerente && in_array($d['drive_state'],['failed','retry'],true)): ?><form method="post"><?php invoiceHidden('drive_retry'); ?><input type="hidden" name="document_id" value="<?= (int)$d['id'] ?>"><button class="primary-button"><?= it('retry_drive') ?></button></form><?php endif; ?></div>
<?php if ($d['drive_state']!=='verified'): ?><details><summary><?= it('archive_details') ?></summary><p><?= it('server_copy_pending') ?></p><p><?= it('attempts') ?>: <?= (int)($d['drive_attempts'] ?? 0) ?>/9</p><?php if ($d['next_attempt_at']): ?><p><?= it('next_attempt') ?>: <?= ie(invoiceTime($d['next_attempt_at'])) ?></p><?php endif; ?><?php if ($d['last_error']): ?><p><?= it($d['last_error']) ?></p><?php endif; ?></details><?php endif; ?></article><?php endforeach; ?></div>
<?php if ($hasMore): ?><a data-save-context="page" data-save-context-target="#invoice-results" class="invoice-link-action" href="<?= ie(invoiceUrl('documents',['state'=>$filters['state'],'q'=>$filters['q'],'before'=>end($documents)['id']])) ?>"><?= it('older') ?></a><?php endif; ?></section>
