<?php if (!defined('INVOICE_VIEW')) { http_response_code(404); exit; } ?>
<section class="card"><h2><?= it('tab_overview') ?></h2><?php require $viewRoot.'/filters.php'; ?>
<div id="invoice-results" class="invoice-metrics"><?php foreach (['total'=>'invoices','archived'=>'drive_verified','review'=>'needs_attention','csv'=>'csv_pending'] as $key=>$label): ?><a class="invoice-metric" href="<?= ie(invoiceUrl('documents',['state'=>match($key){'archived'=>'drive_verified','review'=>'needs_attention','csv'=>'csv_pending',default=>''}])) ?>"><strong><?= $stats[$key] ?></strong><span><?= it($label) ?></span></a><?php endforeach; ?></div>
<?php if ($canRun): $eligible=0; foreach ($accounts as $a) if ((int)$a['is_active'] && !$a['archived_at'] && $readiness[$a['id']]==='ready' && (!$filters['account'] || $filters['account']===(int)$a['id']) && (!$filters['portal'] || $filters['portal']===$a['portal']) && (!$filters['property'] || (str_starts_with($filters['property'],$a['id'].':') && isset($repository->collectionProperties((int)$a['id'])[explode(':',$filters['property'],2)[1]])))) $eligible++; ?>
<div class="invoice-options"><h3><?= it('collect') ?></h3><p><?= it('collection_scope') ?> <strong><?= $eligible ?></strong> · <?= ie($period) ?></p><p><?= it('background') ?></p><form method="post"><?php invoiceHidden('collect',$filters['account']); ?><button class="primary-button" <?= !$eligible?'disabled':'' ?>><?= it('collect_filtered') ?></button></form><?php if (!$eligible): ?><p><?= it('no_ready_accounts') ?></p><?php endif; ?></div>
<?php endif; ?></section>
<section class="card"><h2><?= it('month_by_account') ?></h2><div class="invoice-record-grid">
<?php $shown=0; foreach ($accounts as $a): if ($a['archived_at'] || ($filters['account'] && $filters['account']!==(int)$a['id']) || ($filters['portal'] && $filters['portal']!==$a['portal']) || ($filters['property'] && !str_starts_with($filters['property'],$a['id'].':'))) continue; $shown++; ?>
<article class="invoice-record"><div class="invoice-record-heading"><div><p class="invoice-kicker"><?= ie(InvoiceAccounts::PORTALS[$a['portal']]) ?></p><h3><?= ie($a['label']) ?></h3></div><?php invoiceStatus((int)$a['is_active']?'active':'inactive'); ?></div>
<dl class="invoice-facts"><div><dt><?= it('access') ?></dt><dd><?php invoiceStatus($readiness[$a['id']]); ?></dd></div><div><dt><?= it('last_collection_month') ?></dt><dd><?php invoiceStatus($a['month_state']); ?></dd></div><div><dt><?= it('invoices') ?></dt><dd><?= (int)$a['document_count'] ?></dd></div><div><dt><?= it('last_success') ?></dt><dd><?= ie(invoiceTime($a['last_success'])) ?></dd></div><div><dt><?= it('next_collection') ?></dt><dd><?= ie(InvoiceWorkspace::nextRun($a) ?? InvoiceText::get('manual_only')) ?></dd></div></dl>
<?php if ($a['month_error']): ?><p><?= it($a['month_error']) ?></p><?php endif; ?>
<div class="form-actions"><a href="<?= ie(invoiceUrl('documents',['account'=>$a['id']])) ?>"><?= it('view_invoices') ?></a><a href="<?= ie(invoiceUrl('activity',['account'=>$a['id']])) ?>"><?= it('view_activity') ?></a><?php if ($isGerente): ?><a href="<?= ie(invoiceUrl('accounts',['edit'=>$a['id']])) ?>"><?= it('manage_account') ?></a><?php endif; ?></div></article>
<?php endforeach; ?><?php if (!$shown): ?><p><?= it('no_accounts_filter') ?></p><?php endif; ?></div></section>
<section class="card"><h2><?= it('integrations') ?></h2><dl class="invoice-facts"><div><dt>Google Drive</dt><dd><?php invoiceStatus($driveSettings['state'] ?? 'not_configured',match($driveSettings['state'] ?? ''){'ready'=>'drive_connection_ready','configured'=>'drive_connection_pending',default=>'drive_not_configured'}); ?></dd></div><div><dt>TOConline</dt><dd><?php invoiceStatus('integration_unavailable','toconline_setup_pending'); ?></dd></div><div><dt>WhatsApp</dt><dd><?php invoiceStatus(!empty($notifications['enabled'])?'enabled':'disabled',!empty($notifications['enabled'])?'alerts_enabled':'alerts_disabled'); ?></dd></div></dl><?php if ($isGerente): ?><a class="invoice-link-action" href="<?= ie(invoiceUrl('settings')) ?>"><?= it('tab_settings') ?></a><?php endif; ?></section>
