<?php if (!defined('INVOICE_VIEW') || !$isGerente) { http_response_code(404); exit; } ?>
<section class="card"><h2><?= it('agent_title') ?></h2><p><?= it('agent_description') ?></p>
<p><?= it('agent_last_seen') ?>: <?= ie(invoiceTime($agentStatus['last_seen'] ?? null)) ?></p>
<p><?= it('agent_last_probe') ?>: <?= ie(invoiceTime($agentStatus['probe_at'] ?? null)) ?> — <?= ($agentStatus['probe_code'] ?? '')==='ok' ? it('browser_ready') : it('preflight_required') ?></p>
<form method="post"><?php invoiceHidden('agent_mode'); ?><label class="field"><span><?= it('agent_mode_label') ?></span><select name="agent_mode"><?php foreach (['local','paused','windows'] as $mode): ?><option value="<?= ie($mode) ?>" <?= $agentStatus['mode']===$mode?'selected':'' ?>><?= it('agent_mode_'.$mode) ?></option><?php endforeach; ?></select></label><button class="primary-button" <?= !$vault?'disabled':'' ?>><?= it('save') ?></button></form>
<details class="invoice-options"><summary><?= it('agent_setup') ?></summary><p><?= it('agent_pair_note') ?></p>
<form method="post"><?php invoiceHidden('agent_pair'); ?><button class="invoice-secondary" <?= !$vault?'disabled':'' ?>><?= it('agent_pair') ?></button></form>
<?php if ($agentStatus['paired']): ?><form method="post"><?php invoiceHidden('agent_revoke'); ?><button class="invoice-secondary"><?= it('agent_revoke') ?></button></form><?php endif; ?>
</details></section>
<section class="card"><h2><?= it('drive') ?></h2><p class="invoice-destination">daniel.ciorcas@welcomehostel.pt</p><div class="invoice-status-line"><?php invoiceStatus($driveSettings['state'] ?? 'not_configured',match($driveSettings['state'] ?? ''){'ready'=>'drive_connection_ready','configured'=>'drive_connection_pending',default=>'drive_not_configured'}); ?></div>
<?php $driveCanConnect=$vault && $vault->has('drive-oauth.enc'); if (!$driveCanConnect): ?><p><?= it('drive_setup_pending') ?></p><?php endif; ?>
<form method="post" action="invoice-drive.php"><?php invoiceHidden('connect'); ?><button class="primary-button" <?= !$driveCanConnect?'disabled':'' ?>><?= it('drive_connect') ?></button></form>
<details class="invoice-options"><summary><?= it('drive_manage') ?></summary><form method="post"><?php invoiceHidden('drive_settings'); ?><fieldset <?= !$driveCanConnect?'disabled':'' ?>><label class="field"><span><?= it('folder_id') ?></span><input type="text" name="folder_id" value="<?= ie($driveSettings['folder_id'] ?? '') ?>" maxlength="128" required></label><div class="form-actions"><button class="primary-button" name="action" value="drive_settings"><?= it('save') ?></button><button class="primary-button" name="action" value="drive_test"><?= it('drive_test') ?></button></div></fieldset></form><p><?= it('drive_setup_note') ?></p></details>
<details><summary><?= it('storage_rules') ?></summary><p><?= it('drive_note') ?></p></details></section>
<section class="card"><h2>TOConline</h2><p><?= it('toconline_setup_pending') ?></p><details><summary><?= it('processing_details') ?></summary><p><?= it('toconline_note') ?></p><p><?= it('airbnb_pipeline') ?></p></details></section>
<section class="card"><h2><?= it('failure_alerts') ?></h2><div class="invoice-status-line"><?php invoiceStatus(!empty($notifications['enabled'])?'enabled':'disabled',!empty($notifications['enabled'])?'alerts_enabled':'alerts_disabled'); ?></div><p><?= it('alerts_summary') ?></p>
<form method="post"><?php invoiceHidden('notifications'); ?><div class="form-grid"><label class="field"><span><?= it('manager') ?></span><select name="recipient"><option value=""><?= it('select_manager') ?></option><?php foreach ($managers as $manager): ?><option value="<?= (int)$manager['id'] ?>" <?= (int)($notifications['recipient_user_id'] ?? 0)===(int)$manager['id']?'selected':'' ?>><?= ie($manager['display_name']) ?></option><?php endforeach; ?></select></label><label class="check-row"><input type="checkbox" name="enabled" <?= !empty($notifications['enabled'])?'checked':'' ?>><span><?= it('enable_alerts') ?></span></label></div>
<details><summary><?= it('advanced_template') ?></summary><label class="field"><span><?= it('template_name') ?></span><input type="text" name="template_name" value="<?= ie($notifications['template_name'] ?? 'invoice_collection_failed_v1') ?>" pattern="[a-z0-9_]+" required></label><p><?= it('alerts_note') ?></p><p><?= it('template_approval_note') ?></p></details><button class="primary-button"><?= it('save_alerts') ?></button></form></section>
<section class="card"><details><summary><?= it('technical_diagnostics') ?></summary><p><?= $service->browserReady()?it('browser_ready'):it('preflight_required') ?></p><p><?= it('worker_last_seen') ?>: <?= ie(invoiceTime($settings['worker_seen_at'] ?? null)) ?></p><p><?= it('browser_last_check') ?>: <?= ie(invoiceTime($settings['browser_checked_at'] ?? null)) ?></p>
<?php if ($accounts): ?><form method="post"><?php invoiceHidden('preflight',(int)$accounts[0]['id']); ?><button class="invoice-secondary"><?= it('preflight') ?></button></form><?php endif; ?></details></section>
