<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/Invoices/InvoiceWorkspace.php';
$workspaceChecks=0;
function checkWorkspace(bool $ok,string $label): void {global $workspaceChecks;if(!$ok)throw new RuntimeException($label);$workspaceChecks++;}
function rejectWorkspace(callable $fn,string $code): void {try{$fn();}catch(RuntimeException $e){checkWorkspace($e->getMessage()===$code,'Expected '.$code);return;}throw new RuntimeException('Expected rejection: '.$code);}
$accounts=new InvoiceAccounts($pdo);$service=new InvoiceService($pdo);$workspace=new InvoiceWorkspace($pdo);
$wa=$accounts->create('booking','Workspace A',['wa'=>'One','wb'=>'Two','wc'=>'Three'],'password');
$wb=$accounts->create('booking','Workspace B',['wa'=>'Different property'],'password');
checkWorkspace($accounts->active($wa)&&!(int)$accounts->get($wa)['enabled'],'Manual activity is independent of schedule');
$targets=[['account_id'=>$wa,'property_id'=>'wa'],['account_id'=>$wa,'property_id'=>'wb'],['account_id'=>$wb,'property_id'=>'wa']];
$key=hash('sha256','workspace-request');
$batch=$service->collectBatch($targets,'2029-02',1,$key);
checkWorkspace($service->collectBatch($targets,'2029-02',1,$key)===$batch,'Double click does not duplicate a request');
$filters=InvoiceWorkspace::filters(['period'=>'2029-02']);
$tasks=$workspace->tasks($filters,false,$batch);
checkWorkspace(count($tasks)===3,'Distinct accounts and properties queue separately');
$overlap=$service->collectBatch($targets,'2029-02',1,hash('sha256','workspace-overlap'));
checkWorkspace(array_column($workspace->tasks($filters,false,$overlap),'id')===array_column($tasks,'id'),'Overlapping request shares active tasks');
$pdo->prepare("UPDATE invoice_tasks SET state='completed',active_key=NULL,finished_at='2029-03-01 04:00:00',imported_count=2 WHERE account_id=? AND period='2029-02'")->execute([$wa]);
$pdo->prepare("UPDATE invoice_tasks SET state='failed',active_key=NULL,result_code='network_error' WHERE account_id=? AND period='2029-02'")->execute([$wb]);
$summary=$workspace->batches($filters)[0]['summary'];
checkWorkspace($summary['state']==='partial'&&$summary['completed']===1&&$summary['failed']===1&&$summary['total']===2&&$summary['new']===4,'Partial request counts accounts, not properties');
checkWorkspace(count($workspace->batches(array_replace($filters,['period'=>'2029-01'])))===0,'Historical activity respects period');
checkWorkspace(count($workspace->tasks(array_replace($filters,['account'=>$wa]),false,$batch))===2,'Activity respects account filter');
checkWorkspace(count($workspace->tasks(array_replace($filters,['property'=>$wa.':wb']),false,$batch))===1,'Property filter includes account identity');
$job=(int)$tasks[0]['id'];
checkWorkspace(count($workspace->tasks($filters,false,null,PHP_INT_MAX,$job))===1,'Exact retry task lookup respects scope');
checkWorkspace(!$workspace->tasks(array_replace($filters,['period'=>'2029-01']),false,null,PHP_INT_MAX,$job),'Exact retry cannot escape period');
$pdo->prepare("INSERT INTO invoice_documents(account_id,property_id,invoice_number,period,format,period_basis,pipeline_state,sha256,size_bytes,created_at)VALUES(?,'wa','INV_100%','2029-02','pdf','issue_month','collected',?,100,'2029-03-01 04:00:00')")->execute([$wa,hash('sha256','workspace-pdf')]);$doc=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO invoice_document_delivery(document_id,company_state,drive_state,toconline_state)VALUES(?,'validated','failed','pending')")->execute([$doc]);
$f=array_replace($filters,['account'=>$wa]);
checkWorkspace($workspace->stats($f)['review']===1&&count($workspace->documents(array_replace($f,['state'=>'needs_attention'])))===1,'Attention counter and link include failed Drive uploads');
checkWorkspace(count($workspace->documents(array_replace($f,['q'=>'_100%'])))===1,'Invoice search treats wildcard characters literally');
checkWorkspace(count($workspace->documents(array_replace($f,['q'=>'_10%'])))===0,'Wildcard search cannot expand');
checkWorkspace(!$workspace->documents(array_replace($f,['property'=>$wa.':wb'])),'Invoice property scope is enforced');
$queue=$service->enqueue('collect','wc','2029-02',1,null,$wa);
$accounts->updateDetails($wa,'Renamed',['wa'=>'One renamed','wb'=>'Two'],true);
checkWorkspace(count($accounts->properties($wa))===3&&count($accounts->collectionProperties($wa))===2,'Removed property retains historical identity but is not collected');
checkWorkspace($pdo->query("SELECT state FROM invoice_tasks WHERE id=$queue")->fetchColumn()==='cancelled','Removed property cancels pending collection');
rejectWorkspace(fn()=>$service->collectBatch([['account_id'=>$wa,'property_id'=>'wc']],'2029-02',1,hash('sha256','inactive-property')),'property_inactive');
$service->saveSchedule(true,5,'04:00',$wa);
$queue=$service->enqueue('collect','wa','2029-03',1,null,$wa);
$accounts->setLifecycle($wa,false,true);
checkWorkspace(!$accounts->active($wa)&&!(int)$accounts->get($wa)['enabled'],'Archiving disables schedule and manual collection');
checkWorkspace($pdo->query("SELECT state FROM invoice_tasks WHERE id=$queue")->fetchColumn()==='cancelled','Archiving cancels queued work');
checkWorkspace(count($workspace->documents($f))===1&&count($workspace->tasks($f,false,$batch))===2,'Archiving preserves invoices and history');
rejectWorkspace(fn()=>$service->enqueue('collect','wa','2029-03',1,null,$wa),'account_inactive');
$accounts->setLifecycle($wa,true);
checkWorkspace($accounts->active($wa)&&!(int)$accounts->get($wa)['enabled'],'Restoring does not silently enable scheduling');
$air=$accounts->create('airbnb','Airbnb test',['seed'=>'Initial'],'password');
$associations=InvoiceWorkspace::propertiesFromInput(['property_ids'=>['','',''],'property_labels'=>['Loft','Studio','Flat']],'airbnb');
$accounts->updateDetails($air,'Airbnb test',$associations,true);
checkWorkspace(count($accounts->activeProperties($air))===4&&array_keys($accounts->collectionProperties($air))===['account'],'Multiple Airbnb properties retain one original account export');
$airbatch=$service->collectBatch([['account_id'=>$air,'property_id'=>'account']],'2029-02',1,hash('sha256','airbnb-batch'));
checkWorkspace(count($workspace->tasks($filters,false,$airbatch))===1,'One Airbnb export job per account');
rejectWorkspace(fn()=>InvoiceWorkspace::propertiesFromInput(['property_ids'=>['a','a'],'property_labels'=>['One','Two']],'booking'),'invalid_request');
$tmp=sys_get_temp_dir().'/workspace-vault-'.bin2hex(random_bytes(5));mkdir($tmp,0700);file_put_contents($tmp.'/master.key',random_bytes(32));chmod($tmp.'/master.key',0600);
try {
 $vault=new InvoiceVault($tmp);$accounts->saveCredentials($vault,$wa,['identifier'=>'fixture','password'=>'not-a-real-password']);
 $pdo->prepare("UPDATE invoice_accounts SET login_verified_at='2029-01-01 00:00:00',enabled=1 WHERE id=?")->execute([$wa]);
 $accounts->saveCredentials($vault,$wa,['identifier'=>'','password'=>'','auth_method'=>'password']);
 checkWorkspace((int)$accounts->get($wa)['enabled']===1&&!empty($accounts->get($wa)['login_verified_at']),'Saving unchanged credentials preserves validation and schedule');
 $accounts->saveCredentials($vault,$wa,['password'=>'changed-fixture']);
 checkWorkspace(!(int)$accounts->get($wa)['enabled']&&empty($accounts->get($wa)['login_verified_at']),'Changed credentials require new validation');
 checkWorkspace(InvoiceWorkspace::integration($accounts->get($air),$vault)==='integration_setup','An account without a connector cannot be presented as ready');
} finally {foreach(glob($tmp.'/*')?:[] as $file)unlink($file);rmdir($tmp);}
$pdo->prepare("UPDATE invoice_tasks SET state='failed',result_code='network_error' WHERE account_id=? AND property_id='wb' AND period='2029-02'")->execute([$wa]);
$month=array_column($workspace->accounts('2029-02'),'month_state','id');
checkWorkspace($month[$wa]==='partial','Overview surfaces failed property even when another succeeded');
$scoped=array_column($workspace->accounts('2029-02',$wa.':wb'),null,'id');
checkWorkspace($scoped[$wa]['month_state']==='failed'&&(int)$scoped[$wa]['document_count']===0,'Overview account card respects property filter');
$a=['enabled'=>1,'is_active'=>1,'archived_at'=>null,'schedule_day'=>5,'schedule_time'=>'04:00','scheduled_current'=>false];
checkWorkspace(InvoiceWorkspace::nextRun($a,new DateTimeImmutable('2029-03-06T12:00:00Z'))==='05/03/2029 04:00','Overdue unqueued collection is not silently advanced a month');
$a['scheduled_current']=true;
checkWorkspace(InvoiceWorkspace::nextRun($a,new DateTimeImmutable('2029-03-06T12:00:00Z'))==='05/04/2029 04:00','Queued monthly request advances next schedule');
echo "Invoice workspace checks passed: $workspaceChecks\n";
