<?php
declare(strict_types=1);
require __DIR__.'/invoices.php';
require_once dirname(__DIR__).'/src/Invoices/InvoiceRemoteAgent.php';
require_once dirname(__DIR__).'/src/Invoices/InvoiceTestControl.php';
$pdo->exec("CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT,display_name TEXT,mobile TEXT,role TEXT,is_active INTEGER);
INSERT INTO users VALUES(7,'gerente','Fixture owner','351900000001','gerente',1);
CREATE TABLE auth_audit_log(id INTEGER PRIMARY KEY,actor_user_id INTEGER,action TEXT,details_json TEXT,ip_key TEXT);
CREATE TABLE role_permissions(role TEXT,permission TEXT);
ALTER TABLE invoice_notification_settings ADD COLUMN recipient_user_id INTEGER;
ALTER TABLE invoice_notification_settings ADD COLUMN template_name TEXT;
UPDATE invoice_notification_settings SET enabled=0,template_name='invoice_collection_failed';
DELETE FROM invoice_tasks; DELETE FROM invoice_batches; DELETE FROM invoice_batch_tasks;
DELETE FROM invoice_account_settings; DELETE FROM invoice_property_settings;
DELETE FROM invoice_account_properties WHERE account_id=1;
INSERT INTO invoice_account_properties VALUES(1,'1140306','Welcome'),(1,'539828','City');
UPDATE invoice_accounts SET enabled=0,login_verified_at='2026-09-01 00:00:00' WHERE id=1;");
$tmp=sys_get_temp_dir().'/test-control-'.bin2hex(random_bytes(8)); mkdir($tmp,0700);
InvoiceVault::atomicWrite($tmp.'/master.key',random_bytes(32));
$vault=new InvoiceVault($tmp); $agent=new InvoiceRemoteAgent($pdo,['private_dir'=>$tmp,'whatsapp'=>['secrets_file'=>$tmp.'/whatsapp.json']]);
$control=new InvoiceTestControl($pdo,$vault,$agent);
$token=$agent->pair();
$send=static fn(array $request)=>$agent->handle($token,$request);
$reject=static function(callable $fn,string $code): void {
    try { $fn(); } catch (Throwable $e) { checkInvoice($e->getMessage()===$code,'Expected '.$code.', got '.$e->getMessage()); return; }
    throw new RuntimeException('Missing rejection '.$code);
};
try {
    $reject(fn()=>$send(['action'=>'control_status','period'=>'2026-07']),'forbidden');
    checkInvoice($control->provisionOnce()==='granted','Explicit grant targets the exact two active properties');
    checkInvoice($control->provisionOnce()==='already_recorded','Provisioning is one-time');
    $send(['action'=>'ping']); $send(['action'=>'probe','code'=>'ok']); $send(['action'=>'control_resume']);
    $before=$vault->read('windows-agent.enc');
    $status=$send(['action'=>'control_status','period'=>'2026-07']);
    checkInvoice($before===$vault->read('windows-agent.enc'),'Status is not a worker heartbeat');
    checkInvoice($status['notifications']['owner_id']===7 && $status['notifications']['owner_mobile_suffix']==='0001','Only fixed owner metadata is returned');
    $reject(fn()=>$send(['action'=>'control_status','period'=>null]),'invalid_request');
    $reject(fn()=>$send(['action'=>'control_status','period'=>'2026-07','account_id'=>2]),'invalid_request');
    $reject(fn()=>$send(['action'=>'control_enable_alerts','recipient'=>8]),'forbidden');
    $reject(fn()=>$send(['action'=>'control_enable_alerts','recipient'=>7]),'invalid_request');
    InvoiceVault::atomicWrite($tmp.'/whatsapp.json',json_encode(['access_token'=>'fake-provider-secret','phone_number_id'=>'123']));
    $send(['action'=>'control_enable_alerts','recipient'=>7]);
    checkInvoice((int)$pdo->query('SELECT enabled FROM invoice_notification_settings')->fetchColumn()===1,'Owner alerts enabled with existing configuration');
    $vault->save('account-1-automation.enc',['captcha_mode'=>'test','captcha_api_key'=>str_repeat('a',32),'deny_loopback'=>true]);
    $send(['action'=>'control_enable_captcha']);
    checkInvoice($vault->read('account-1-automation.enc')['captcha_mode']==='collection','Explicit opt-in covers collections');
    checkInvoice(!str_contains(json_encode($send(['action'=>'control_status','period'=>'2026-07'])),str_repeat('a',32)),'Status excludes CAPTCHA key');
    $request=['action'=>'control_collect','period'=>'2026-07','request_id'=>str_repeat('b',32)];
    $reject(fn()=>$send($request),'auth_invalid');
    $vault->save('account-1-credentials.enc',['identifier'=>'fixture','password'=>'fixture']);
    InvoiceVault::atomicWrite($tmp.'/account-1-map.json',json_encode(['version'=>3,'validated'=>true,'portal'=>'booking','accountId'=>1,'strategy'=>'booking-finance-v1','properties'=>['1140306'=>[],'539828'=>[]]]));
    $batch=$send($request);
    checkInvoice($batch===$send($request),'Response replay cannot create another batch');
    checkInvoice((int)$pdo->query('SELECT COUNT(*) FROM invoice_tasks')->fetchColumn()===2,'Both properties share one request');
    unlink($vault->path('test-control-'.str_repeat('b',32).'.enc'));
    checkInvoice($send($request)===$batch,'Database request key recovers a lost receipt');
    $reject(fn()=>$send(array_replace($request,['period'=>'2026-06'])),'invalid_request');
    $offer=$send(['action'=>'claim','claim_id'=>str_repeat('c',32)])['job'];
    checkInvoice($offer['input']['automation']['captcha_api_key']===str_repeat('a',32),'Authorized collection receives the provider key through the encrypted transport');
    $reject(fn()=>$send(['action'=>'control_pause']),'worker_busy');
    $pdo->exec("UPDATE users SET is_active=0 WHERE id=7");
    $reject(fn()=>$send(['action'=>'control_status','period'=>'2026-07']),'forbidden');
    $pdo->exec("UPDATE users SET is_active=1 WHERE id=7");
    $send(['action'=>'control_revoke']);
    checkInvoice($control->provisionOnce()==='already_recorded','Deploy never re-enables a revoked grant');
    $reject(fn()=>$send(['action'=>'control_status','period'=>'2026-07']),'forbidden');
    $grant=$vault->read(InvoiceTestControl::GRANT); $grant['enabled']=true; $vault->save(InvoiceTestControl::GRANT,$grant);
    $paired=$vault->read('windows-agent.enc');$rotated=str_repeat('d',64);$paired['token_hash']=hash('sha256',$rotated);$vault->save('windows-agent.enc',$paired);
    $reject(fn()=>$agent->handle($rotated,['action'=>'control_status','period'=>'2026-07']),'forbidden');
    echo "Scoped Booking test control, permissions, revocation and idempotence passed.\n";
} finally { foreach(glob($tmp.'/*')?:[] as $file) unlink($file); rmdir($tmp); }
